### ISSUE TITLE
Support request for latest CUDA + Python + Torch

### ISSUE THREAD

**Issue by manchuwook** [thu-ml/SageAttention#262]
# CUDA 13.0 Compilation Compatibility Issue on Windows

## Subject
**[Windows] NVCC 13.0 Compilation Fails with "A single input file is required for a non-link phase when an outputfile is specified"**

## Environment
- **OS**: Windows 11
- **GPU**: NVIDIA GeForce RTX 5090 (Blackwell, sm_120)
- **CUDA**: 13.0
- **Python**: 3.13
- **PyTorch**: 2.9.0.dev20250909+cu130 (nightly)
- **Visual Studio**: 2022 Community (14.44.35207)

## Issue Description

SageAttention compilation fails on Windows with CUDA 13.0 due to NVCC's stricter command-line parsing introduced in CUDA 13.0. The error occurs during ninja build execution:

```
nvcc fatal : A single input file is required for a non-link phase when an outputfile is specified
```

The problematic command generated by PyTorch's build system includes flags that NVCC 13.0 cannot properly parse:
```bash
nvcc --generate-dependencies-with-compile --dependency-output [path].obj.d [other flags] -c file.cu -o output.obj
```

## Root Cause Analysis

NVIDIA made changes to NVCC's command-line parser in CUDA 13.0 that conflict with how PyTorch's ninja build system constructs compilation commands. Specifically:

1. **Dependency Generation Flags**: The combination of `--generate-dependencies-with-compile` and `--dependency-output` with other flags causes parsing conflicts
2. **Command Structure**: NVCC 13.0 is more strict about flag ordering and combinations
3. **Windows-Specific**: This issue appears to be Windows-specific due to path handling and flag escaping differences

## Impact

This affects users with:
- RTX 50xx series GPUs (requiring CUDA 12.8+ for sm_120 support)
- CUDA 13.0 installations
- Windows development environments
- Cutting-edge PyTorch nightly builds

Many RTX 5090 users require CUDA 13.0 for optimal performance and compatibility.

## Attempted Solutions

We've tried several workarounds:
1. Environment variables (`USE_NINJA=0`, `DISTUTILS_USE_SDK=1`)
2. PyTorch cpp_extension patching
3. Real-time ninja file modification
4. Direct setup.py compilation approaches

None successfully resolve the core NVCC command-line parsing issue.

### Short-term
1. **Pre-built Wheels**: Provide CUDA 13.0 Windows wheels for major Python versions (3.11, 3.12, 3.13)
2. **Build Instructions**: Document CUDA 12.8 as the recommended version for Windows compilation
3. **Alternative Toolchain**: Investigate MSBuild instead of ninja for Windows CUDA 13.0

### Long-term
1. **NVCC Compatibility**: Work with NVIDIA and PyTorch teams to resolve command-line generation
2. **Build System Updates**: Modify build scripts to generate CUDA 13.0-compatible commands
3. **Conditional Compilation**: Detect CUDA version and adjust build flags accordingly

## Workaround for Users

Current recommended approach for RTX 5090 users:
1. Use CUDA 12.8 instead of 13.0 (performance impact is minimal)
2. Install available pre-built wheels when possible
3. Use SageAttention 1.0 (Triton-only) as fallback: `pip install sageattention==1.0.6`

## Additional Context

This issue affects the broader PyTorch ecosystem, not just SageAttention. Similar reports exist for other CUDA extensions on Windows with CUDA 13.0. The issue appears to be a compatibility gap that will likely require coordination between multiple teams (NVIDIA, PyTorch, extension maintainers).

We appreciate the work on SageAttention and understand this is a broader ecosystem challenge. Any guidance or timeline for CUDA 13.0 Windows support would be helpful for the community.

## System Information
```
PyTorch: 2.9.0.dev20250909+cu130
CUDA available: True
CUDA version: 13.0
Device name: NVIDIA GeForce RTX 5090
Compute Capability: (12, 0)
```

**Comment by manchuwook** [comment]
I used to see these things with #PRAGMAS before in the past - I don't know if there is an equivalent.

**Comment by Arcitec** [comment]
Thanks for documenting the issue.

Since this is an issue in Ninja, did you file a ticket there?

**Comment by igor-iki** [comment]
so anyone have wheel for cuda13? cant build sageattention with  pytorch 2.10.0.dev20250926+cu130
`error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v13.0\\bin\\nvcc.EXE' failed with exit code 4294967295
    [end of output]`

**Comment by manchuwook** [comment]
> Thanks for documenting the issue.
> 
> Since this is an issue in Ninja, did you file a ticket there?

I had not, but I can look into it.

**Comment by alessandro893** [comment]
I managed to build SageAttention for Pytorch 2.9.0 + cuda 13

SageAttention2:

[sageattention-2.2.0-cp312-cp312-win_amd64.zip](https://github.com/user-attachments/files/22992388/sageattention-2.2.0-cp312-cp312-win_amd64.zip)

SageAttention3:

[sageattn3-1.0.0-cp312-cp312-win_amd64.zip](https://github.com/user-attachments/files/22992505/sageattn3-1.0.0-cp312-cp312-win_amd64.zip)

**Comment by rugabunda** [comment]
@manchuwook  here is a patch I made that allowed me to build it:

https://github.com/thu-ml/SageAttention/issues/228#issuecomment-3483944852

 I made a script that automates this process that was tested with the latest bleeding cuda 13.0; pytorch 2.9; Python 3.12.11.  Probably earlier versions that were also broken.

Activate your environment 

`git clone https://github.com/thu-ml/SageAttention.git`

Drop the code below into a file in its root and run:

`python build_sage.py`
```
# Sageattention build patcher
import os
import subprocess
import sys

# Apply patches
print("Applying patches...")
files = ['csrc/fused/fused.cu', 'csrc/qattn/qk_int_sv_f16_cuda_sm80.cu']

for f in files:
    if os.path.exists(f):
        with open(f, 'r') as file:
            content = file.read()
        if '#include <vector>' not in content:
            content = '#include <vector>\n#include <typeindex>\n' + content
            with open(f, 'w') as file:
                file.write(content)
            print(f"✓ Patched {f}")

# Patch setup.py
with open('setup.py', 'r') as f:
    setup_content = f.read()

setup_content = setup_content.replace(
    'CXX_FLAGS = ["/O2", "/openmp"]',
    'CXX_FLAGS = ["/O2", "/openmp", "/std:c++20", "/DENABLE_BF16"]'
)
setup_content = setup_content.replace('"-std=c++17"', '"-std=c++20"')

with open('setup.py', 'w') as f:
    f.write(setup_content)

print("✓ Patches applied successfully")

# Set environment variables
os.environ['EXT_PARALLEL'] = '4'
os.environ['NVCC_APPEND_FLAGS'] = '--threads 8'
os.environ['MAX_JOBS'] = '32'

# Uninstall old version first
subprocess.run([sys.executable, '-m', 'pip', 'uninstall', 'sageattention', '-y'])

# Build and install with pip
print("\nBuilding with pip...")
subprocess.run([sys.executable, '-m', 'pip', 'install', '.', '--no-build-isolation'], check=True)
print("\n✓ Build complete!")
```

![Image](https://github.com/user-attachments/assets/89b1eaf9-d419-4ef0-8f27-7eff26c53c56)

**Comment by aaronjolson** [comment]
Wow, thanks @rugabunda ! I did not think this would work for me since I am running in a conda env, but it totally did, this is great!

**Comment by JasonHoku** [comment]
> [@manchuwook](https://github.com/manchuwook) here is a patch I made that allowed me to build it:
> 
> [#228 (comment)](https://github.com/thu-ml/SageAttention/issues/228#issuecomment-3483944852)
> 
> I made a script that automates this process that was tested with the latest bleeding cuda 13.0; pytorch 2.9; Python 3.12.11. Probably earlier versions that were also broken.
> 
> Activate your environment
> 
> `git clone https://github.com/thu-ml/SageAttention.git`
> 
> Drop the code below into a file in its root and run:
> 
> `python build_sage.py`
> 
> ```
> # Sageattention build patcher
> import os
> import subprocess
> import sys
> 
> # Apply patches
> print("Applying patches...")
> files = ['csrc/fused/fused.cu', 'csrc/qattn/qk_int_sv_f16_cuda_sm80.cu']
> 
> for f in files:
>     if os.path.exists(f):
>         with open(f, 'r') as file:
>             content = file.read()
>         if '#include <vector>' not in content:
>             content = '#include <vector>\n#include <typeindex>\n' + content
>             with open(f, 'w') as file:
>                 file.write(content)
>             print(f"✓ Patched {f}")
> 
> # Patch setup.py
> with open('setup.py', 'r') as f:
>     setup_content = f.read()
> 
> setup_content = setup_content.replace(
>     'CXX_FLAGS = ["/O2", "/openmp"]',
>     'CXX_FLAGS = ["/O2", "/openmp", "/std:c++20", "/DENABLE_BF16"]'
> )
> setup_content = setup_content.replace('"-std=c++17"', '"-std=c++20"')
> 
> with open('setup.py', 'w') as f:
>     f.write(setup_content)
> 
> print("✓ Patches applied successfully")
> 
> # Set environment variables
> os.environ['EXT_PARALLEL'] = '4'
> os.environ['NVCC_APPEND_FLAGS'] = '--threads 8'
> os.environ['MAX_JOBS'] = '32'
> 
> # Uninstall old version first
> subprocess.run([sys.executable, '-m', 'pip', 'uninstall', 'sageattention', '-y'])
> 
> # Build and install with pip
> print("\nBuilding with pip...")
> subprocess.run([sys.executable, '-m', 'pip', 'install', '.', '--no-build-isolation'], check=True)
> print("\n✓ Build complete!")
> ```
> 
> ![Image](https://github.com/user-attachments/assets/89b1eaf9-d419-4ef0-8f27-7eff26c53c56)

YOU LEGEND!!

After an hour of struggling to build sageattention on the latest UI version, I'm happy to report:
This worked perfectly and easily on a newer version, ComfyUI 0.12.3 with  Python version: 3.13.11 and pytorch version: 2.10.0+cu130

**Comment by KLL535** [comment]
Does anyone have a whl sageattn3 for: 
CUDA: 13.1
Python: 3.13
PyTorch: 2.11.0.dev20260211+cu130
Does not compile (error C2872: 'std': ambiguous symbol)

**Comment by sideraldx** [comment]
> > [@manchuwook](https://github.com/manchuwook) Aquí hay un parche que hice que me permitió construirlo:
> > [#228 (comentario)](https://github.com/thu-ml/SageAttention/issues/228#issuecomment-3483944852)
> > Hice un script que automatiza este proceso que fue probado con la última versión de Bleeding Cuda 13.0; PyTorch 2.9; Python 3.12.11. Probablemente versiones anteriores que también estaban rotas.
> > Activa tu entorno
> > `git clone https://github.com/thu-ml/SageAttention.git`
> > Coloque el siguiente código en un archivo en su raíz y ejecute:
> > `python build_sage.py`
> > ```
> > # Sageattention build patcher
> > import os
> > import subprocess
> > import sys
> > 
> > # Apply patches
> > print("Applying patches...")
> > files = ['csrc/fused/fused.cu', 'csrc/qattn/qk_int_sv_f16_cuda_sm80.cu']
> > 
> > for f in files:
> >     if os.path.exists(f):
> >         with open(f, 'r') as file:
> >             content = file.read()
> >         if '#include <vector>' not in content:
> >             content = '#include <vector>\n#include <typeindex>\n' + content
> >             with open(f, 'w') as file:
> >                 file.write(content)
> >             print(f"✓ Patched {f}")
> > 
> > # Patch setup.py
> > with open('setup.py', 'r') as f:
> >     setup_content = f.read()
> > 
> > setup_content = setup_content.replace(
> >     'CXX_FLAGS = ["/O2", "/openmp"]',
> >     'CXX_FLAGS = ["/O2", "/openmp", "/std:c++20", "/DENABLE_BF16"]'
> > )
> > setup_content = setup_content.replace('"-std=c++17"', '"-std=c++20"')
> > 
> > with open('setup.py', 'w') as f:
> >     f.write(setup_content)
> > 
> > print("✓ Patches applied successfully")
> > 
> > # Set environment variables
> > os.environ['EXT_PARALLEL'] = '4'
> > os.environ['NVCC_APPEND_FLAGS'] = '--threads 8'
> > os.environ['MAX_JOBS'] = '32'
> > 
> > # Uninstall old version first
> > subprocess.run([sys.executable, '-m', 'pip', 'uninstall', 'sageattention', '-y'])
> > 
> > # Build and install with pip
> > print("\nBuilding with pip...")
> > subprocess.run([sys.executable, '-m', 'pip', 'install', '.', '--no-build-isolation'], check=True)
> > print("\n✓ Build complete!")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ![Image](https://github.com/user-attachments/assets/89b1eaf9-d419-4ef0-8f27-7eff26c53c56)
> 
> ¡¡ERES LEYENDA!!
> 
> Después de una hora de luchar para crear sageattention en la última versión de la interfaz de usuario, me complace informar: Esto funcionó perfecta y fácilmente en una versión más nueva, ComfyUI 0.12.3 con la versión de Python: 3.13.11 y la versión de PyTorch: 2.10.0+cu130

brother could you make a tutorial, I'm in the same problem, but I really can't solve it

**Comment by OchotaDariusz** [comment]
MOST IMPORTANT: DO NOT USE POWERSHELL, use CMD or native command prompt for vs


Fix from GPT that worked for me:

1. Open **x64 Native Tools Command Prompt for VS 2022** and run these commands:

```bat
call "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build\vcvars64.bat"

set "CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v13.0"
set "CUDA_HOME=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v13.0"
set "INCLUDE=%CUDA_PATH%\include\cccl;%INCLUDE%"

cd /d S:\ComfyUI_windows_portable\SageAttention
```

2. In `setup.py` change **NVCC_FLAGS** at 51 and 54 line of code:

```diff
- "-std=c++17",
+ "-std=c++20",
```

and in `csrc/utils.cuh` in line 32:

```diff
- TORCH_CHECK(x.sizes() == torch::IntArrayRef({__VA_ARGS__}), \
+ TORCH_CHECK(x.sizes().equals(torch::IntArrayRef({__VA_ARGS__})), \
```

Then:

```bat
rmdir /S /Q build
"S:\ComfyUI_windows_portable\python_embeded\python.exe" setup.py install
```


Summary from gpt about issue:

**Windows + CUDA 13 + PyTorch 2.13 compatibility issue**

> **Windows: build failure with CUDA 13.0 / PyTorch 2.13.0+cu130**
>
> On Windows, SageAttention 2.2.0 fails to compile with CUDA 13.0 and PyTorch 2.13.0+cu130.
>
> There appear to be two compatibility issues:
>
> 1. `setup.py` passes `-std=c++17` to NVCC, while the PyTorch 2.13 headers used in this configuration require C++20 syntax. This results in errors such as:
>
> ```text
> c10/util/StringUtil.h(169): error: expected an expression
> c10/core/AutogradState.h(89): error: data member initializer is not allowed
> c10/core/AutogradState.h(90): error: data member initializer is not allowed
> ```
>
> Changing the NVCC flag from:
>
> ```python
> "-std=c++17"
> ```
>
> to:
>
> ```python
> "-std=c++20"
> ```
>
> allows the compilation to proceed successfully in this environment.
>
> 2. `CHECK_SHAPE` in `csrc/utils.cuh` uses `==` between `IntArrayRef` types. With the current PyTorch headers this results in an ambiguous `operator==`. Replacing:
>
> ```cpp
> x.sizes() == torch::IntArrayRef({...})
> ```
>
> with:
>
> ```cpp
> x.sizes().equals(torch::IntArrayRef({...}))
> ```
>
> resolves that error.
>
> **Tested configuration:**
>
> ```text
> Windows
> CUDA 13.0
> PyTorch 2.13.0+cu130
> Visual Studio Build Tools 2022 / MSVC 14.44
> SageAttention 2.2.0
> ```
>
> After these changes, SageAttention compiled successfully.
>
> It would be useful to consider making the CUDA standard compatible with the PyTorch version/toolchain automatically, or otherwise documenting the required C++ standard for CUDA 13 / recent PyTorch versions.

Good luck!

**Comment by rgibson2525-afk** [comment]
Same issue with Linux, torch 2.14.0+cu130, Python 3.12, the ATen.h "#error C++20 or later compatible compiler is required.

Workaround:
sed -i 's/-std=c++17/-std=c++20/g' setup.py
