### ISSUE TITLE
upgraded too far?

### ISSUE THREAD

**Issue by CHagenlo** [thu-ml/SageAttention#233]
updated my pc and nvidia installed cuda 13.0 and cuDNN 9.11.0 so now i get an error when trying to use sage attention in comfyui saying

<img width="707" height="413" alt="Image" src="https://github.com/user-attachments/assets/9cc7fe8d-538b-4a8e-9ffa-c7ecdbe7d7d7" />

**Comment by Heliumrich** [comment]
That's nightly cuda

I tried latest stable (PyTorch 2.8.0 cuda 12.9)
but when I tried to  recompile it from source it made an error (with `pip install -e .` because the install.py one didn't work)

```
LINK : error LNK2001: unresolved external symbol PyInit__qattn_sm80
      C:\Users\Niels\AppData\Local\Temp\tmpcpnkwa1t.build-temp\Release\sageattention._qattn_sm80\csrc\qattn\_qattn_sm80.cp312-win_amd64.lib : fatal error LNK1120: 1 unresolved externals
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.44.35207\\bin\\HostX86\\x64\\link.exe' failed with exit code 1120
```

It worked fine on PyTorch 2.7.1 cu128, so maybe we have to wait for them to support above ?


**EDIT:** I was able to compile SageAttention2++ on PyTorch 2.8.0 cu129, after double-checking my env variables, restarting my command prompt, purging pip cache, and building without using the variables for parallel compiling

**Comment by freyandere** [comment]
> That's nightly cuda
> 
> I tried latest stable (PyTorch 2.8.0 cuda 12.9) but when I tried to recompile it from source it made an error (with `pip install -e .` because the install.py one didn't work)
> 
> ```
> LINK : error LNK2001: unresolved external symbol PyInit__qattn_sm80
>       C:\Users\Niels\AppData\Local\Temp\tmpcpnkwa1t.build-temp\Release\sageattention._qattn_sm80\csrc\qattn\_qattn_sm80.cp312-win_amd64.lib : fatal error LNK1120: 1 unresolved externals
>       error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.44.35207\\bin\\HostX86\\x64\\link.exe' failed with exit code 1120
> ```
> 
> It worked fine on PyTorch 2.7.1 cu128, so maybe we have to wait for them to support above ?
> 
> **EDIT:** I was able to compile SageAttention2++ on PyTorch 2.8.0 cu129, after double-checking my env variables, restarting my command prompt, purging pip cache, and building without using the variables for parallel compiling

@NielsGx hey can you please share the compiled Wheel .whl file as ComfyUI moved completely to new Cuda/torch?

**Comment by subspecs** [comment]
This is still an issue
